[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_exercise = "GdopSYJVVgib3WUQsCQRd5k8Kxf3Zth4uBSZ5ifvjM9T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
